package cn.mcmod.sakura.data.client;

import cn.mcmod.sakura.block.BlockRegistry;
import cn.mcmod.sakura.block.ShojiBlock;
import cn.mcmod.sakura.block.foods.TeishokuBlock;
import cn.mcmod.sakura.block.machines.TataraBlock;
import cn.mcmod.sakura.block.noodles.BlockNoodle;
import cn.mcmod_mmf.mmlib.data.AbstractBlockStateProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.FenceBlock;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraftforge.client.model.generators.ConfiguredModel;
import net.minecraftforge.client.model.generators.ModelFile;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.ForgeRegistries;

public class SakuraBlockStateProvider extends AbstractBlockStateProvider {

    public SakuraBlockStateProvider(PackOutput packOutput, String modid, ExistingFileHelper exFileHelper) {
        super(packOutput, modid, exFileHelper);
    }

    @Override
    protected void registerStatesAndModels() {
        // ==============================
        // Simple Cube Blocks (leaves, planks, etc.)
        // ==============================
        simpleBlock(BlockRegistry.SAKURA_LEAVES.get());
        simpleBlock(BlockRegistry.SAKURA_PLANK.get());
        simpleBlock(BlockRegistry.MAPLE_PLANK.get());
        simpleBlock(BlockRegistry.BAMBOO_PLANK.get());

        simpleBlock(BlockRegistry.STRAW_BLOCK.get());

        simpleBlock(BlockRegistry.MAPLE_LEAVES_RED.get());
        simpleBlock(BlockRegistry.MAPLE_LEAVES_YELLOW.get());
        simpleBlock(BlockRegistry.MAPLE_LEAVES_GREEN.get());
        simpleBlock(BlockRegistry.MAPLE_LEAVES_ORANGE.get());

        // Simple cube blocks - world gen
        simpleBlock(BlockRegistry.SAKURA_DIAMOND_ORE.get());
        simpleBlock(BlockRegistry.IRON_SAND.get());

        // Kawara block (full cube)
        simpleBlock(BlockRegistry.KAWARA_BLOCK.get());

        // ==============================
        // Log Blocks
        // ==============================
        log(BlockRegistry.SAKURA_LOG);
        log(BlockRegistry.STRIPPED_SAKURA_LOG);
        log(BlockRegistry.MAPLE_LOG);
        log(BlockRegistry.STRIPPED_MAPLE_LOG);
        log(BlockRegistry.BAMBOO_BLOCK);
        log(BlockRegistry.BAMBOO_BLOCK_SUNBURNT);
        log(BlockRegistry.BAMBOO_CHARCOAL_BLOCK);

        // ==============================
        // Machines with custom models (horizontal facing)
        // ==============================
        horizontalBlock(BlockRegistry.FERMENTER.get(), models().getExistingFile(new ResourceLocation("sakura:block/fermenter")));

        // ==============================
        // Saplings (cross blocks)
        // ==============================
        crossBlock(BlockRegistry.SAKURA_SAPLING);
        crossBlock(BlockRegistry.MAPLE_SAPLING_RED);
        crossBlock(BlockRegistry.MAPLE_SAPLING_YELLOW);
        crossBlock(BlockRegistry.MAPLE_SAPLING_GREEN);
        crossBlock(BlockRegistry.MAPLE_SAPLING_ORANGE);

        // Wild plants (crop blocks with age, using pepper/vanilla crop models)
        // Blockstates are hand-written (not cross blocks) - they use the same models as pepper_crop/vanilla_crop

        // ==============================
        // Crops generated by datagen (BaseCropBlock / Age3CropBlock)
        // ==============================
        stageBlock(BlockRegistry.BUCKWHEAT_CROP, BlockStateProperties.AGE_7);
        stageBlock(BlockRegistry.RAPESEED_CROP, BlockStateProperties.AGE_7);
        stageBlock(BlockRegistry.REDBEAN_CROP, BlockStateProperties.AGE_3);
        stageBlock(BlockRegistry.TARO_CROP, BlockStateProperties.AGE_3);
        stageBlock(BlockRegistry.SOYBEAN_CROP, BlockStateProperties.AGE_3);

        // NOTE: cabbage_crop, radish_crop, onion_crop, seaweed_crop have hand-written
        // blockstate JSON in src/main/resources with custom model names (e.g. cabbage_0
        // instead of cabbage_crop_stage0), so we do NOT generate them here.
        // HighCropBlock crops (tomato, eggplant, pepper, vanilla, grape, hops)
        // and rice crops also have hand-written blockstate JSON files in src/main/resources
        // because they have special upper/lower or custom blockstate properties.

        // ==============================
        // Tatami (horizontal blocks with directional textures)
        // ==============================
        horizontalBlock(BlockRegistry.TATAMI.get(),
                texture("tatami"),
                texture("tatami"),
                texture("tatami"));

        horizontalBlock(BlockRegistry.TATAMI_WAXED.get(),
                texture("tatami"),
                texture("tatami"),
                texture("tatami"));

        facingSlabBlock(BlockRegistry.TATAMI_SLAB_WAXED,
                texture("tatami"),
                texture("tatami"),
                texture("tatami")
        );

        horizontalBlock(BlockRegistry.TATAMI_SUNBURNT.get(),
                texture("tatami_tan"),
                texture("tatami_tan"),
                texture("tatami_tan"));

        facingSlabBlock(BlockRegistry.TATAMI_SLAB,
                texture("tatami"),
                texture("tatami"),
                texture("tatami")
        );
        facingSlabBlock(BlockRegistry.TATAMI_SLAB_SUNBURNT,
                texture("tatami_tan"),
                texture("tatami_tan"),
                texture("tatami_tan")
        );

        // ==============================
        // Stairs
        // ==============================
        stairsBlock((StairBlock) BlockRegistry.SAKURA_STAIRS.get(), texture("plank_sakura"));
        stairsBlock((StairBlock) BlockRegistry.MAPLE_STAIRS.get(), texture("plank_maple"));
        stairsBlock((StairBlock) BlockRegistry.BAMBOO_PLANK_STAIRS.get(), texture("plank_bamboo"));
        stairsBlock((StairBlock) BlockRegistry.BAMBOO_STAIRS.get(), texture("bamboo_block"));
        stairsBlock((StairBlock) BlockRegistry.BAMBOO_STAIRS_SUNBURNT.get(), texture("bamboo_block_sunburnt"));
        stairsBlock((StairBlock) BlockRegistry.STRAW_STAIRS.get(), texture("straw_block"));

        // Kawara (stairs-shaped roof tile, using existing kawara block model as stairs texture)
        stairsBlock((StairBlock) BlockRegistry.KAWARA.get(), texture("kawara_1"));

        // ==============================
        // Slabs
        // ==============================
        slabBlock((SlabBlock) BlockRegistry.SAKURA_SLAB.get(), texture("plank_sakura"), texture("plank_sakura"));
        slabBlock((SlabBlock) BlockRegistry.MAPLE_SLAB.get(), texture("plank_maple"), texture("plank_maple"));
        slabBlock((SlabBlock) BlockRegistry.BAMBOO_PLANK_SLAB.get(), texture("plank_bamboo"), texture("plank_bamboo"));
        slabBlock((SlabBlock) BlockRegistry.BAMBOO_SLAB.get(), texture("bamboo_block"), texture("bamboo_block"));
        slabBlock((SlabBlock) BlockRegistry.BAMBOO_SLAB_SUNBURNT.get(), texture("bamboo_block_sunburnt"), texture("bamboo_block_sunburnt"));
        slabBlock((SlabBlock) BlockRegistry.STRAW_SLAB.get(), texture("straw_block"), texture("straw_block"));

        // ==============================
        // Fences
        // ==============================
        fenceBlock((FenceBlock) BlockRegistry.BAMBOO_FENCE.get(), texture("bamboo_block"));
        fenceBlock((FenceBlock) BlockRegistry.BAMBOO_FENCE_SUNBURNT.get(), texture("bamboo_block_sunburnt"));

        // ==============================
        // Door
        // ==============================
        doorBlockWithRenderType((DoorBlock) BlockRegistry.BAMBOO_DOOR.get(),
                texture("bamboo_door_lower"), texture("bamboo_door_upper"), "cutout");

        // ==============================
        // Fallen Leaves (carpet-like blocks) - each color uses its own model with matching texture
        // ==============================
        simpleBlock(BlockRegistry.FALLEN_LEAVES_RED.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/fallen_leaves")));
        simpleBlock(BlockRegistry.FALLEN_LEAVES_YELLOW.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/fallen_leaves_yellow")));
        simpleBlock(BlockRegistry.FALLEN_LEAVES_ORANGE.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/fallen_leaves_orange")));
        simpleBlock(BlockRegistry.FALLEN_LEAVES_GREEN.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/fallen_leaves_green")));

        // ==============================
        // Tatami Carpets (carpet-like)
        // ==============================
        simpleBlock(BlockRegistry.TATAMI_CARPET.get(),
                models().carpet(blockName(BlockRegistry.TATAMI_CARPET.get()), texture("tatami")));
        simpleBlock(BlockRegistry.TATAMI_CARPET_WAXED.get(),
                models().carpet(blockName(BlockRegistry.TATAMI_CARPET_WAXED.get()), texture("tatami_ns")));
        simpleBlock(BlockRegistry.TATAMI_CARPET_TAN.get(),
                models().carpet(blockName(BlockRegistry.TATAMI_CARPET_TAN.get()), texture("tatami_tan")));
        simpleBlock(BlockRegistry.TATAMI_CARPET_TAN_WAXED.get(),
                models().carpet(blockName(BlockRegistry.TATAMI_CARPET_TAN_WAXED.get()), texture("tatami_tan_ns")));

        // ==============================
        // Decorative blocks with custom Blockbench models
        // Point blockstate to existing model file
        // ==============================
        // Lanterns - LanternBlock has hanging+waterlogged properties; each variant uses its own model with unique textures
        lanternBlock(BlockRegistry.STONE_LANTERN.get(), "stone_lantern");
        lanternBlock(BlockRegistry.COBBLESTONE_LANTERN.get(), "cobblestone_lantern");
        lanternBlock(BlockRegistry.MOSSY_STONE_LANTERN.get(), "mossy_stone_lantern");
        lanternBlock(BlockRegistry.RED_LANTERN.get(), "lantern");
        lanternBlock(BlockRegistry.WHITE_LANTERN.get(), "white_lantern");
        lanternBlock(BlockRegistry.BAMBOO_LANTERN.get(), "bamboo_lantern");

        // Windbell - also LanternBlock
        lanternBlock(BlockRegistry.WINDBELL.get(), "windbell");

        // Andon (paper lamp) - simple block with existing model
        simpleBlock(BlockRegistry.ANDON.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/andon")));

        // Kitunebi (ghost fire) - cross-like block with existing model
        simpleBlock(BlockRegistry.KITUNEBI.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/kitunebi")));

        // Zabuton (floor cushion) - existing model
        simpleBlock(BlockRegistry.ZABUTON.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/zabuton")));

        // Futon (bedding) - existing model
        simpleBlock(BlockRegistry.FUTON.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/futon")));

        // Taiko (drum) - existing model
        simpleBlock(BlockRegistry.TAIKO.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/taiko")));

        // Noren (curtains) - existing noren model
        simpleBlock(BlockRegistry.NOREN_WHITE.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/noren")));
        simpleBlock(BlockRegistry.NOREN_BLUE.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/noren_blue")));
        simpleBlock(BlockRegistry.NOREN_PINK.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/noren_pink")));

        // ==============================
        // Teishoku blocks (new ones) - these have custom models with facing+bites
        // Use the existing model pattern from the other teishoku blocks
        // ==============================
        teishokuBlock(BlockRegistry.TEISHOKU_TEMPURA.get(), "teishoku_tempura");
        teishokuBlock(BlockRegistry.TEISHOKU_FRIED.get(), "teishoku_fried");
        teishokuBlock(BlockRegistry.TEISHOKU_KATSU.get(), "teishoku_katsu");
        teishokuBlock(BlockRegistry.TEISHOKU_BURGER.get(), "teishoku_burger");

        // ==============================
        // Newly Added Blocks (from 1.12.2 port)
        // ==============================

        // -- Machine/Functional Blocks --

        // Barrel Output - horizontal facing, uses existing barrel_1 Blockbench model
        horizontalBlock(BlockRegistry.BARREL_OUT.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/barrel_1")));

        // Tatara - horizontal facing + LIT, uses tatara texture as simple cube
        getVariantBuilder(BlockRegistry.TATARA.get()).forAllStates(state -> {
            boolean lit = state.getValue(TataraBlock.LIT);
            String texName = lit ? "tatara_smelting" : "tatara";
            int yRot = ((int) state.getValue(TataraBlock.FACING).toYRot() + 180) % 360;
            return ConfiguredModel.builder()
                    .modelFile(models().cubeAll(blockName(BlockRegistry.TATARA.get()) + (lit ? "_smelting" : ""), texture(texName)))
                    .rotationY(yRot)
                    .build();
        });

        // Maple Cauldron - simple block with existing Blockbench model
        simpleBlock(BlockRegistry.MAPLE_CAULDRON.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/maple_cauldron")));

        // Maple Spile - horizontal facing with existing Blockbench model
        horizontalBlock(BlockRegistry.MAPLE_SPILE.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/spile")));

        // Shoji - horizontal facing + open state
        getVariantBuilder(BlockRegistry.SHOJI.get()).forAllStates(state -> {
            boolean open = state.getValue(ShojiBlock.OPEN);
            int yRot = ((int) state.getValue(ShojiBlock.FACING).toYRot() + 180) % 360;
            return ConfiguredModel.builder()
                    .modelFile(open
                            ? models().getBuilder("shoji_open").texture("particle", texture("shoji"))
                            : models().getExistingFile(new ResourceLocation("sakura:block/shoji")))
                    .rotationY(yRot)
                    .build();
        });

        // Sushi & Tempura Plates (TeishokuBlock - facing + bites)
        teishokuBlock(BlockRegistry.SUSHI_PLATE.get(), "sushi_plate");
        teishokuBlock(BlockRegistry.TEMPURA_PLATE.get(), "tempura_plate");

        // -- Simple Cube Blocks --

        // Sakura Diamond Block - simple cube
        simpleBlock(BlockRegistry.SAKURA_DIAMOND_BLOCK.get());

        // Noodle Dough Blocks - each has 8 cutting stages (0-7) using noodle_N models with texture overrides
        // Hand-written blockstates in src/main/resources override these, but keep data gen in sync.
        noodleCuttingBlock(BlockRegistry.RAMEN_BLOCK.get(), "ramen");
        noodleCuttingBlock(BlockRegistry.SOBA_BLOCK.get(), "soba");
        noodleCuttingBlock(BlockRegistry.PASTA_BLOCK.get(), "pasta");

        // Udon block - cutting stages use base noodle_0-7 models (udon texture is already the default)
        noodleCuttingBlock(BlockRegistry.UDON_BLOCK.get(), null);

        // Udon unfinished - uses existing Blockbench model
        simpleBlock(BlockRegistry.UDON_UNFINISHED.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/udon_unfinished")));

        // -- Ume (Plum) Tree --
        // No ume_log_top texture exists, so use ume_log for both side and end
        axisBlock(BlockRegistry.UME_LOG.get(), texture("ume_log"), texture("ume_log"));
        simpleBlock(BlockRegistry.UME_LEAVES.get(),
                models().cubeAll(blockName(BlockRegistry.UME_LEAVES.get()), texture("ume_leaves")));
        crossBlock(BlockRegistry.UME_SAPLING);

        // Chestnut Burr - bush block with cross model, uses chestnut_burr_0 texture
        simpleBlock(BlockRegistry.CHESTNUT_BURR.get(),
                models().cross(blockName(BlockRegistry.CHESTNUT_BURR.get()), texture("chestnut_burr_0")).renderType("cutout"));

        // -- Decorative Blocks --

        // Mushroom Fallen Leaves - carpet-like with mushrooms (existing Blockbench model)
        simpleBlock(BlockRegistry.MUSHROOM_FALLEN_LEAVES.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/fallen_leaves_mushroom")));

        // Straw Web - uses existing Blockbench model
        simpleBlock(BlockRegistry.STRAW_WEB.get(),
                models().getExistingFile(new ResourceLocation("sakura:block/straw_web")));

        // -- Tatami Variants (1.12.2 full blocks and half slabs) --
        horizontalBlock(BlockRegistry.TATAMI_TAN.get(),
                texture("tatami_tan"),
                texture("tatami_tan"),
                texture("tatami_tan"));

        horizontalBlock(BlockRegistry.TATAMI_TAN_NS.get(),
                texture("tatami_tan_ns"),
                texture("tatami_tan_ns"),
                texture("tatami_tan_ns"));

        horizontalBlock(BlockRegistry.TATAMI_NS.get(),
                texture("tatami_ns"),
                texture("tatami_ns"),
                texture("tatami_ns"));

        facingSlabBlock(BlockRegistry.TATAMI_HALF,
                texture("tatami"),
                texture("tatami"),
                texture("tatami")
        );
        facingSlabBlock(BlockRegistry.TATAMI_NS_HALF,
                texture("tatami_ns"),
                texture("tatami_ns"),
                texture("tatami_ns")
        );
        facingSlabBlock(BlockRegistry.TATAMI_TAN_HALF,
                texture("tatami_tan"),
                texture("tatami_tan"),
                texture("tatami_tan")
        );
        facingSlabBlock(BlockRegistry.TATAMI_TAN_NS_HALF,
                texture("tatami_tan_ns"),
                texture("tatami_tan_ns"),
                texture("tatami_tan_ns")
        );

        // ==============================
        // Hot spring water - fluid block, just use simple block
        // ==============================
        simpleBlock(BlockRegistry.HOT_SPRING_WATER.get(),
                models().getBuilder(blockName(BlockRegistry.HOT_SPRING_WATER.get()))
                        .texture("particle", texture("hot_spring_water_still")));
    }

    /**
     * Helper to generate blockstates for LanternBlock (hanging + waterlogged).
     * Uses the same model for all states since these are custom Blockbench models.
     */
    private void lanternBlock(Block block, String modelName) {
        ModelFile model = models().getExistingFile(new ResourceLocation("sakura:block/" + modelName));
        getVariantBuilder(block).forAllStatesExcept(state -> {
            return net.minecraftforge.client.model.generators.ConfiguredModel.builder()
                    .modelFile(model)
                    .build();
        });
    }

    /**
     * Helper to generate blockstates for TeishokuBlock (facing + bites 0-3).
     */
    private void teishokuBlock(Block block, String name) {
        getVariantBuilder(block).forAllStates(state -> {
            int bites = state.getValue(TeishokuBlock.BITES);
            String suffix = bites > 0 ? "_" + bites : "";
            int yRot = ((int) state.getValue(TeishokuBlock.FACING).toYRot() + 180) % 360;
            return net.minecraftforge.client.model.generators.ConfiguredModel.builder()
                    .modelFile(models().getExistingFile(new ResourceLocation("sakura:block/" + name + suffix)))
                    .rotationY(yRot)
                    .build();
        });
    }

    /**
     * Helper to generate blockstates for noodle cutting blocks (cutting 0-7).
     * If noodleType is non-null, uses "{type}_noodle_{stage}" models (texture-overridden variants).
     * If noodleType is null, uses base "noodle_{stage}" models directly.
     */
    private void noodleCuttingBlock(Block block, String noodleType) {
        getVariantBuilder(block).forAllStates(state -> {
            int cutting = state.getValue(BlockNoodle.CUTTING);
            String modelName = noodleType != null
                    ? noodleType + "_noodle_" + cutting
                    : "noodle_" + cutting;
            return net.minecraftforge.client.model.generators.ConfiguredModel.builder()
                    .modelFile(models().getExistingFile(new ResourceLocation("sakura:block/" + modelName)))
                    .build();
        });
    }

    private String blockName(Block block) {
        return ForgeRegistries.BLOCKS.getKey(block).getPath();
    }
}
