package cn.mcmod.sakura.item.enums;

public enum SakuraNormalItemSet {
    BAMBOO("bamboo"),
    BAMBOO_SUNBURNT("bamboo_sunburnt"),
    BAMBOO_CHARCOAL("bamboo_charcoal"),
    LUMBER_BAMBOO("lumber_bamboo"),
    LUMBER_SAKURA("lumber_sakura"),
    LUMBER_MAPLE("lumber_maple"),
    STRAW("straw"),
    CHARCOAL_POWDER("charcoal_powder"),
    SALT("salt"),
    ALKALINE("alkaline"),
    IMOGARA("imogara"),
    BROWN_RICE("brown_rice"),
    RICE("rice"),
    FLOUR("flour"),
    FLOUR_BUCKWHEAT("flour_buckwheat"),
    FLOUR_RICE("flour_rice"),
    DOUGH("dough"),
    DOUGH_BUCKWHEAT("dough_buckwheat"),
    DOUGH_RICE("dough_rice"),
    KOUJI("kouji"),
    SOYSAUCE("soysauce"),
    DASHI("dashi"),
    MISO("miso"),
    MIRIN("mirin"),
    SAKE_KASU("sake_kasu"),
    TEMPURA_BATTER("tempura_batter"),
    MOLASSES("molasses"),
    YEAST("yeast"),
    KAESHI("kaeshi"),
    NOODLE_SOUP("noodle_soup"),
    NUKA("nuka"),
    MIRIN_KASU("mirin_kasu"),
    SILK("silk"),
    HOP("hop"),
    CURRY_POWDER("curry_powder"),
    RAMEN_RAW("ramen_raw"),
    UDON_RAW("udon_raw"),
    SOBA_RAW("soba_raw"),
    PASTA_RAW("pasta_raw"),
    MAPLE_SYRUP("maple_syrup"),
    SEAWEED("seaweed"),
    WORCESTER_SAUCE("worcester_sauce"),
    MAYO("mayo"),
    VINEGAR("vinegar"),
    CURRY_SAUCE("curry_sauce"),
    WHITE_SAUCE("white_sauce"),
    CHESTNUT_BURRS("chestnut_burrs"),
    CHESTNUT("chestnut"),
    PEPPERCORN_GREEN("peppercorn_green"),
    PEPPERCORN_RED("peppercorn_red"),
    BLACK_PEPPER("black_pepper"),
    WHITE_PEPPER("white_pepper"),
    VANILLA("vanilla"),
    VANILLA_ROAST("vanilla_roast"),
    GREEN_TEA_LEAVES("green_tea_leaves"),
    BLACK_TEA_LEAVES("black_tea_leaves"),
    EARL_GREY_LEAVES("earl_grey_leaves"),
    FRUIT_TEA_LEAVES("fruit_tea_leaves"),
    MOCHA("mocha"),
    RICE_TEA_LEAVES("rice_tea_leaves"),
    MINT("mint"),
    MINT_TEA_LEAVES("mint_tea_leaves"),
    COIN("coin"),
    ZUKU("zuku"),
    ZUKU_INGOT("zuku_ingot"),
    SAGEGANE("sagegane"),
    TAMAHAGANE("tamahagane"),
    STEEL_INGOT("steel_ingot"),
    MISO_BALL("miso_ball"),
    DRIED_IMOGARA("dried_imogara"),
    IMOGARANAWA_PIECE("imogaranawa_piece"),
    EMPTY_BOTTLE("empty_bottle"),
    BENTO_BOX("bento_box");
    private final String name;
    private SakuraNormalItemSet(String name) {
        this.name = name;
    }
    public String getName() {
        return name;
    }
}
